# what language the build will be configured for
language: python
sudo: no

# what versions of python to evaluate
python:
  - "3.6"

# only test the master branch
branches:
  only:
    - travisci

before_install:
      #    - install miniconda
      #    - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
      #    - chmod +x miniconda.sh
      #    - ./miniconda.sh -b -p "$PWD/miniconda/"
      #    - export PATH="$PWD/miniconda/bin/:$PATH"
      #    - yes|conda update conda > /dev/null

# install packages necessary for CI test, set up env
install:
  - pip install coverage
  - pip install coveralls
  - pip install pytest
  - pip install flake8
  - pip install -r requirements.txt
    #  - yes|conda env create -f environment.yml
    #  - source activate yeast 
    
before_script:
  - export PYTHONPATH=$PYTHONPATH:$(pwd)
#  - "flake8 expressyeaself"

script:
  - flake8
#  - coverage run -m unittest discover

# calculate and report code coverage
after_success:
  - coveralls
  - coverage report

# whether or not to eb notified everytime someone pushes
notifications:
    email: true
