# what language the build will be configured for
language: python
sudo: no

# Setting some global variables
env:
    global:
    - KERAS_BACKEND = tensorflow

# Python versions to run
python:
  - "3.6"

# Only test the master branch
branches:
  only:
      #- master
    - coverage 

before_install:
      #    - install miniconda
      #    - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
      #    - chmod +x miniconda.sh
      #    - ./miniconda.sh -b -p "$PWD/miniconda/"
      #    - export PATH="$PWD/miniconda/bin/:$PATH"
      #    - yes|conda update conda > /dev/null

# install packages necessary for CI test, set up env
install:
  - pip install coverage
  - pip install coveralls
  - pip install pytest
  - pip install flake8
  - pip install -r requirements.txt
    #- pip install -e
    #  - yes|conda env create -f environment.yml
    #  - source activate yeast 
    
before_script:
  - export PYTHONPATH=$PYTHONPATH:$(pwd)

script:
  - flake8
    #  - coverage run #-m unittest discover
    #- py.test #-s --pyargs expressyeaself --cov-report term-missing --cov=expressyeaself --cov-config .coveragerc
    #- py.test
  - python -m pytest

# calculate and report code coverage
after_success:
  - coveralls
  - coverage report

# Email notifications
notifications:
    email: true
