language: python

sudo: no

python:
    - '3.6'

env:
    global:
    - KERAS_BACKEND=tensorflow

before_install:
    #install miniconda
    - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
    - chmod +x miniconda.sh
    - ./miniconda.sh -b -p "$PWD/miniconda/"
    - export PATH="$PWD/miniconda/bin/:$PATH"
    - yes|conda update conda>/dev/null

install:
    - yes|conda env create -f environment.yml
    - source activate yeast

branches:
    only:
    - master

before_script:
#    -"flake8 speedcom"
    - export KERAS_BACKEND=tensorflow

script:
    - py.test coveralls/tests.py --doctest-modules --pep8 coveralls -v --cov coveralls --cov-report term-missing
    
after_success:
    - coverage report
    - coveralls

notifications:
    email: true


